name: Create Azure Resource Group

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  create-resource-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
    
      - name: Login to Azure
      - uses: azure/login@v1
        with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Resource Group
        uses: azure/arm-deploy@v1
        with:
          scope: "subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          template: "./azure-resource-group.json"
          parameters: "./azure-resource-group.parameters.json"
          deploymentName: your-resource-group-name
